-- ============================================================
-- NAP TINTAS · LOJA ONLINE — SCHEMA SUPABASE
-- Rode este arquivo no SQL Editor do seu projeto Supabase
-- (Dashboard > SQL Editor > New query > cole > Run).
-- Depois rode o seed.sql para carregar o catalogo inicial.
-- ============================================================

-- ---------- CATEGORIAS (as "estantes" da loja; admin cria novas) ----------
create table if not exists categorias (
  id          text primary key,           -- slug: tintas, texturas, equipamentos...
  label       text not null,              -- nome exibido: "Tintas"
  emoji       text default '🎨',
  ordem       int not null default 0,
  criado_em   timestamptz not null default now()
);

-- ---------- PRODUTOS (vitrine e catalogo da loja) ----------
create table if not exists produtos (
  id          bigint generated by default as identity primary key,
  cat         text not null,              -- tintas | texturas | massas | acessorios
  marca       text not null,
  nome        text not null,
  descricao   text,                       -- descricao longa (opcional, admin)
  rendimento  text,                       -- ex.: "350 m2/galao"
  embalagem   text,                       -- ex.: "Galao 3,6L"
  preco       numeric(10,2) not null,
  preco_de    numeric(10,2),              -- preco "De" riscado (oferta de/para)
  cor         text,                       -- cor de acento do card (hex)
  swatch      text,                       -- amostra da cor do produto (hex)
  imagem_url  text,                       -- foto do produto (opcional)
  destaque    boolean not null default false,  -- aparece em "Queridinhos"
  ativo       boolean not null default true,
  ordem       int not null default 0,
  criado_em   timestamptz not null default now()
);

-- ---------- BANNERS (carrossel da bio e da loja; gerido pelo admin) ----------
create table if not exists banners (
  id          bigint generated by default as identity primary key,
  slot        text not null check (slot in ('bio','loja')),
  titulo      text,
  alt         text,
  imagem_url  text not null,
  href        text default '/pedidos',
  ativo       boolean not null default true,
  ordem       int not null default 0,
  criado_em   timestamptz not null default now()
);

-- ---------- CLIENTES (cadastro simples da loja) ----------
create table if not exists clientes (
  id          bigint generated by default as identity primary key,
  nome        text not null,
  whatsapp    text not null,
  email       text,
  criado_em   timestamptz not null default now()
);

-- ---------- PEDIDOS (registro dos pedidos finalizados no WhatsApp) ----------
create table if not exists pedidos (
  id          bigint generated by default as identity primary key,
  cliente_id  bigint references clientes(id),
  itens       jsonb not null,             -- [{produto_id, nome, qtd, preco}]
  total       numeric(10,2) not null,
  status      text not null default 'novo',  -- novo | atendido | cancelado
  criado_em   timestamptz not null default now()
);

-- ---------- ADMINS (quem pode escrever; ver README) ----------
create table if not exists admins (
  user_id     uuid primary key references auth.users(id) on delete cascade,
  nome        text,
  criado_em   timestamptz not null default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- Leitura publica do que e vitrine; escrita so para admins.
-- ============================================================
alter table categorias enable row level security;
alter table produtos enable row level security;
alter table banners  enable row level security;
alter table clientes enable row level security;
alter table pedidos  enable row level security;
alter table admins   enable row level security;

create or replace function is_admin() returns boolean
language sql stable security definer set search_path = public as
$$ select exists (select 1 from admins where user_id = auth.uid()); $$;

-- vitrine: qualquer visitante le o que esta ativo
create policy "categorias: leitura publica" on categorias
  for select using (true);
create policy "categorias: escrita admin" on categorias
  for all using (is_admin()) with check (is_admin());
create policy "produtos: leitura publica" on produtos
  for select using (ativo = true or is_admin());
create policy "banners: leitura publica" on banners
  for select using (ativo = true or is_admin());

-- escrita: somente admins
create policy "produtos: escrita admin" on produtos
  for all using (is_admin()) with check (is_admin());
create policy "banners: escrita admin" on banners
  for all using (is_admin()) with check (is_admin());

-- clientes: qualquer visitante pode se cadastrar; so admin le
create policy "clientes: insert publico" on clientes
  for insert with check (true);
create policy "clientes: leitura admin" on clientes
  for select using (is_admin());

-- pedidos: insert publico (registro da compra); gestao so admin
create policy "pedidos: insert publico" on pedidos
  for insert with check (true);
create policy "pedidos: leitura admin" on pedidos
  for select using (is_admin());
create policy "pedidos: update admin" on pedidos
  for update using (is_admin()) with check (is_admin());

-- admins: somente admins veem a lista
create policy "admins: leitura admin" on admins
  for select using (is_admin());

-- ============================================================
-- STORAGE (fotos de produto e banners enviados pelo admin)
-- Crie um bucket PUBLICO chamado "midia" no Dashboard > Storage.
-- ============================================================
